# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6fb0326ac1fbf7f78da57548f6236cd4a975b4bc159a65e9fd460dc3129c45abfe181cb454d63b6e63c164f94bd1975dccdb7c831db4b97b38fa0f5df491aaf

test:
  secret_key_base: b0691ef7e6531fa79691f970043a56e87eaa15c896ba394c1d02202baf8e8798ed63e995e20d1885a66fba52b239ea8324ea9f76107465c3540ce4fe969cd6c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
